@admin_token = 63cc81195fccb04b1f32f2d148faf11dbb825374
@user_token = 8a52aa41234b3d885b122192d8d45390c1afc8ae

###

# регистрация пользователя
POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Dow",
  "email": "ilyich@mail.ru",
  "password": "Sdgsgjsfj@3324",
  "company": "Mail.ru",
  "position": "manager"
}

###

# подтверждение пользователя
POST http://127.0.0.1:8000/api/v1/user/register/confirm
Content-Type: application/json

{
  "email": "ilyich@mail.ru",
  "token": "3281dfc94c991c485"
}

###

# логин пользователя
POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "ilyich@mail.ru",
  "password": "DFgdfgjk4e43@#"
}

###

# сброс пароля пользователя
POST http://127.0.0.1:8000/api/v1/user/password_reset
Content-Type: application/json

{
  "email": "ilyich@mail.ru"
}

###

# подтверждение сброса пароля пользователя
POST http://127.0.0.1:8000/api/v1/user/password_reset/confirm
Content-Type: application/json

{
  "email": "ilyich@mail.ru",
  "token": "80c5f87c6023dfa950abe8d29bfd3340dd6b7457845b",
  "password": "DFgdfgjk4e43@#"
}

###
# получаем детали пользователя
GET http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token {{admin_token}}

###

# меняем детали пользователя
POST http://127.0.0.1:8000/api/v1/user/details
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "position": "CEO"
}

###

# просмотр контактов пользователя
GET http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token {{user_token}}

###

# добавляем контакт пользователя
POST http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "city": "Moscow",
  "street": "Tverskaya str.",
  "phone": "+77951455886"
}

###

# удаляем контакт пользователя
DELETE http://127.0.0.1:8000/api/v1/user/contact
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "items": "4"
}

###

# обновляем прайс от партнера
POST http://127.0.0.1:8000/api/v1/partner/update
Content-Type: application/json
Authorization: Token {{admin_token}}

{
  "url": "https://raw.githubusercontent.com/netology-code/python-final-diplom/master/data/shop1.yaml"
}

###

# просмотр статуса партнера
GET http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token {{admin_token}}

###

# изменяем статус партнера
POST http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token {{admin_token}}

{
  "state": "on"
}

###

# просмотр заказов партнера
GET http://127.0.0.1:8000/api/v1/partner/orders
Content-Type: application/json
Authorization: Token {{admin_token}}

###

# просмотр категорий
GET http://127.0.0.1:8000/api/v1/categories
Content-Type: application/json
Authorization: Token {{user_token}}

###

# просмотр магазинов
GET http://127.0.0.1:8000/api/v1/shops
Content-Type: application/json
Authorization: Token {{user_token}}

###

# просмотр продуктов
GET http://127.0.0.1:8000/api/v1/products?shop_id=1&category_id=224
Content-Type: application/json
Authorization: Token {{user_token}}

###

# просмотр корзины
GET http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token {{user_token}}

###

# добавить позиции в корзину
POST http://127.0.0.1:8000/api/v1/basket
Content-Type: application/x-www-form-urlencoded
Authorization: Token {{user_token}}

items=[{"product_info": 5,"quantity": 1}]

###

# редактировать количество товаров в корзину
PUT http://127.0.0.1:8000/api/v1/basket
Content-Type: application/x-www-form-urlencoded
Authorization: Token {{user_token}}

items=[{"id": 1,"quantity": 2}]

###

# удалить товаровы из корзину
DELETE http://127.0.0.1:8000/api/v1/basket
Content-Type: application/x-www-form-urlencoded
Authorization: Token {{user_token}}

items=1

###

# разместить заказ
POST http://127.0.0.1:8000/api/v1/order
Content-Type: application/x-www-form-urlencoded
Authorization: Token {{user_token}}

id=1&contact=3

###

# получить мои заказы
GET http://127.0.0.1:8000/api/v1/order
Content-Type: application/x-www-form-urlencoded
Authorization: Token {{user_token}}

id=1&contact=3

###
